# Generated by Django 3.2.7 on 2021-09-27 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='first_name',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='last_name',
            new_name='passwd',
        ),
    ]
